name: CI

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    npm:
        uses: "friendfetcher/nodejs-template/.github/workflows/npm-script.yml@main"
        with:
            node_version: 16.17.0
            script: ${{ matrix.script }}
        strategy:
            matrix:
                script:
                    - npm run lint
                    - npm run prettier
                    - npm run app:test
                    - |
                        npm run app:build
                        npm exec -w app -- node dist/index.js &> app.log &
                        export PROCESS="${!}"
                        npm run integration:test
                        kill "${PROCESS}"
