name: NPM Script

on:
    workflow_call:
        inputs:
            node_version:
                description: The version of node to use
                required: true
                type: string
            script:
                description: A script to run before the Pulumi command
                required: true
                type: string
            aws_region:
                default: us-east-1
                description: The AWS region to use
                required: false
                type: string
            aws_role:
                description: The AWS role to assume
                default: ""
                required: false
                type: string
            aws_session_name:
                description: The AWS session name
                default: ""
                required: false
                type: string
            ref:
                description: The git ref to checkout
                required: false
                type: string
            repository:
                description: The git repository to checkout
                required: false
                type: string
            environment:
                description: An environment to use
                required: false
                type: string

permissions:
    id-token: write
    contents: read
    deployments: write

jobs:
    run:
        name: Run NPM Script
        runs-on: ubuntu-22.04
        environment: ${{ inputs.environment }}
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ inputs.ref }}
                  repository: ${{ inputs.repository }}
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ inputs.node_version }}
                  cache: npm
            - if: inputs.aws_role != '' && inputs.aws_session_name != ''
              name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-region: ${{ inputs.aws_region }}
                  role-to-assume: ${{ inputs.aws_role }}
                  role-session-name: ${{ inputs.aws_session_name }}
            - run: echo '${{ toJSON(github) }}'
            - run: npm ci
            - run: ${{ inputs.script }}
