name: Pulumi

on:
    workflow_call:
        secrets:
            pulumi_access_token:
                description: The Pulumi token
                required: true
            gh_token:
                description: The GitHub token
                required: false
        inputs:
            pulumi_working_dir:
                default: packages/pulumi
                description: The directory where the Pulumi configuration is located
                required: false
                type: string
            pulumi_command:
                default: preview
                description: The Pulumi command to run
                required: false
                type: string
            pulumi_stack:
                default: preview
                description: The Pulumi stack to run the command for
                required: false
                type: string
            aws_region:
                default: us-east-1
                description: The AWS region to use
                required: false
                type: string
            aws_role:
                description: The AWS role to assume
                required: true
                type: string
            aws_session_name:
                description: The AWS session name
                required: true
                type: string
            node_version:
                description: The version of node to use
                required: true
                type: string
            script:
                description: A script to run before the Pulumi command
                default: ""
                required: false
                type: string
            ref:
                description: The git ref to checkout
                required: false
                type: string
            repository:
                description: The git repository to checkout
                required: false
                type: string

permissions:
    id-token: write
    contents: read

jobs:
    run:
        name: Run Pulumi
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ inputs.ref }}
                  repository: ${{ inputs.repository }}
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ inputs.node_version }}
                  cache: npm
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-region: ${{ inputs.aws_region }}
                  role-to-assume: ${{ inputs.aws_role }}
                  role-session-name: ${{ inputs.aws_session_name }}
            - run: npm ci
            - if: inputs.script != ''
              run: ${{ inputs.script }}
            - uses: pulumi/actions@v3
              with:
                  command: ${{ inputs.pulumi_command }}
                  stack-name: ${{ inputs.pulumi_stack }}
                  comment-on-pr: ${{ inputs.pulumi_command == 'preview' }}
                  github-token: ${{ secrets.gh_token }}
                  work-dir: ${{ inputs.pulumi_working_dir }}
              env:
                  PULUMI_ACCESS_TOKEN: ${{ secrets.pulumi_access_token }}
