name: Tag Deploy

on:
    workflow_call:
        inputs:
            environment:
                description: The environment that was deployed
                required: true
                type: string
            ref:
                description: The git ref to checkout
                required: false
                type: string
            repository:
                description: The git repository to checkout
                required: false
                type: string

permissions:
    contents: write

jobs:
    run:
        name: Run Tag Deploy
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ inputs.ref }}
                  repository: ${{ inputs.repository }}
            - run: |
                  export TIME="$(TZ=GMT date +'%Y-%m-%d_%H-%M-%S')"
                  git tag "${{ inputs.environment }}_latest" --force
                  git tag "${{ inputs.environment }}_${TIME}"
                  git push origin "${{ inputs.environment }}_latest" --force
                  git push origin "${{ inputs.environment }}_${TIME}"
